service: zeong-immigration-infrastruct

useDotenv: true

plugins:
  - serverless-plugin-typescript
custom:
  #stage
  stage: dev
provider:
  name: aws
  #Node.js runtime
  runtime: nodejs16.x
  #Region of deployment
  region: us-east-2
  #Env variables
  environment:
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_USER_CLIENT_ID: ${env:COGNITO_USER_CLIENT_ID}
    ZEONG_TABLE: ${env:ZEONG_TABLE}
  #Custom Attributes for cognito pool
  CognitoAddCustomAttributes:
    CognitoUserPoolIdOutputKey: ${env:COGNITO_USER_POOL_ID} # The key of the outputted UserPool Ref
    CognitoUserPoolClientIdOutputKey: ${env:COGNITO_USER_CLIENT_ID} # The key of the outputted UserPoolClient Ref
    CustomAttributes:
      - AttributeDataType: String
        DeveloperOnlyAttribute: False
        Mutable: True
        Name: 'role' # this will end up being custom:another
        Required: False
  #IAM roles
  iamRoleStatements:
    #Role for Cognito
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:ListUsers
      Resource:
        - 'Fn::GetAtt': [UserPool, Arn]
    #Role for DynamoDB
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'Fn::GetAtt': [ZeongTable, Arn]
    #Role for Elastic Search Cluster
    - Effect: Allow
      Action:
        - es:ESHttpPost
        - es:ESHttpPut
        - es:ESHttpDelete
        - es:ESHttpGet
      Resource:
        - {'Fn::GetAtt': ['ElasticSearchInstance', 'DomainArn']}
        - {
            'Fn::Join':
              [
                '',
                [
                  'Fn::GetAtt': ['ElasticSearchInstance', 'DomainArn'],
                  '/*',
                ],
              ],
          }
      Condition:
        IpAddress:
          aws:SourceIp:
            - '0.0.0.0' # Whitelisted IP
# Lambda Functions
functions:
  app:
    handler: ./src/index.handler
    environment:
      REGION: ${env:REGION}
      COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
      COGNITO_USER_CLIENT_ID: ${env:COGNITO_USER_CLIENT_ID}
      AUTH_FLOW: ${env:AUTH_FLOW}
      elasticURL:
        Fn::GetAtt: [ElasticSearchInstance, DomainEndpoint]
    events:
      - http:
          path: ANY /
          method: get
      - http:
          path: ANY /
          method: post
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email
              - custom:role
      - http: 'ANY {proxy+}'

  cognitoCustomMessageLambda:
    handler: ./src/EDA/post-registration.handler
    events:
      - cognitoUserPool:
          pool: zeong-user-pool
          trigger: PostConfirmation
          existing: true
# Other Resources
resources:
  Resources:
    #cognito user pool
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: zeong-user-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: 'role'
            Required: False
            Mutable: true
            AttributeDataType: String
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ['email']
    # Cognito User Client
    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName:
        GenerateSecret: false
        UserPoolId: {Ref: UserPool}
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - 'ADMIN_NO_SRP_AUTH'
    #Dynamodb Table
    ZeongTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:ZEONG_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
    #ElasticSeach Instance
    ElasticSearchInstance:
      Type: AWS::Elasticsearch::Domain
      Properties:
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: 5.3
        AccessPolicies:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                AWS: '*'
              Action: 'es:*'
              Resource: '*'
              Condition:
                IpAddress:
                  aws:SourceIp: ['182.177.251.40']
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: 'true'
